### ISSUE TITLE
Can't get this to work

### ISSUE THREAD

**Issue by chansearrington** [sanctas/threedy-bambu-lab#1]
Hey @sanctas,

I have a bambu X1 that I'm trying to get setup with this cool card.

I followed the documentation that you have, but I don't think that it's correct. OR I'm missing something.

Also, I noticed that another user @e11en has created a new repo to bring this project back to life and make it work with HACS and other pieces.

https://github.com/e11en/ha-threedy-card

When I follow their documentation, I can get their card to show, but not yours for some reason.

Any ideas?

**Comment by sanctas** [comment]
I'll take a look later. I didn't actually write this, I took it from another repo, I just compiled it to work with HACS. 

It worked when I compiled it but I actually didn't end up using it.

**Comment by sreknob** [comment]
@sanctas - I was just looking to set up my X1C.
Probably best option is to try the fork here https://github.com/xZetsubou/ha-threedy-card which has enabled custom sensor remapping and just map the card to your printer that way. It's mostly functional for me but not fully yet. Will probably need some helper sensors to get things in the format that the card is expecting or wait for better support in one of the forks. I haven't tried this repo yet, just found via searching while looking to solve the same problem.

```
type: custom:threedy-card
base_entity: ''
scale: 0.5
use_24hr: true
round_temperature: true
name: Bambu Lab X1C
printer_type: I3
camera_entity: camera.bambu_lab_x1c_camera
light_entity: light.bambu_lab_x1c_chamber_light
always_show: true
monitored:
  - Status
  - ETA
  - Elapsed
  - Remaining
  - Hotend
  - Bed
  - ChamberTemp
  - CurrentTask
sensors:
  Progress:
    entity: sensor.bambu_lab_x1c_print_progress
  Status:
    entity: sensor.bambu_lab_x1c_current_stage
  CurrentTask:
    name: Current Task
    entity: sensor.bambu_lab_x1c_task_name
  ChamberTemp:
    name: Chamber
    entity: sensor.bambu_lab_x1c_chamber_temperature
  Elapsed:
    entity: sensor.bambu_lab_x1c_start_time
  Remaining:
    entity: sensor.bambu_lab_x1c_remaining_time
  ETA:
    entity: sensor.bambu_lab_x1c_end_time
  Hotend:
    entity: sensor.bambu_lab_x1c_nozzle_temperature
  Bed:
    entity: sensor.bambu_lab_x1c_bed_temperature
```

gets me:
![image](https://github.com/sanctas/threedy-bambu-lab/assets/6324507/df3dcfbc-f445-45f2-bc1a-9df3b637b06c)

Camera doesn't work at the moment but will have to dig in more later.
